services:
  postgres:
    image: postgres:13.16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ${POSTGRE_VOLUME}:/var/lib/postgresql/data
    networks:
      - ${NETWORK}

  ecommerce:
    image: fabricioveronez/fake-shop
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: "${DB_PORT}"
      FLASK_APP: ${FLASK_APP}
    ports:
      - "${ECOMMERCE_PORT}:5000"
    depends_on:
      - postgres
    networks:
      - ${NETWORK}

volumes:
  postgre_data_dev:
  postgre_data_homolog:

networks:
  dev_network:
  homolog_network:
